name: 'Get and Cached dependencies'
description: 'Get and cache dependencies for a project'
runs:
  using: composite
  steps:
    - name: Cached Dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash